--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/JavierLeon9966/Alias
build-by-default: true
branches:
- stable
projects:
  Alias:
    libs:
      - src: poggit/libasynql/libasynql
        branch: "pm5"
        version: ^4.1.0
      - vendor: raw
        src: https://poggit.pmmp.io/r/187615/libMarshal_dev-21.phar # Temporary fix, poggit isn't detecting its builds
...
