name: Alias
main: JavierLeon9966\Alias\Alias
author: Javier Leon9966
version: 1.4.1
api: 4.4.0
mcpe-protocol: [431, 440, 448, 465, 471, 475, 486, 503, 527, 534, 544, 545, 554, 557, 560, 567]
description: Detects players possible alternatives accounts
website: https://github.com/JavierLeon9966/Alias
permissions:
  alias.command.alias:
    description: "Allows the user to see another player's possible accounts"
    default: op
  alias.alerts:
    description: "Allows the user to receive alerts when a player joined with a alternative account"
    default: op
