<?php

/*
 * Auto-generated by libasynql-fx
 * Created from stmt.sql, stmt.sql
 */

declare(strict_types=1);

namespace JavierLeon9966\Alias;

use Generator;
use JavierLeon9966\Alias\libs\_bc46b7a33061b3b0\poggit\libasynql\DataConnector;
use JavierLeon9966\Alias\libs\_bc46b7a33061b3b0\SOFe\AwaitGenerator\Await;

final class RawQueries{
	public function __construct(private DataConnector $conn) {}

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql/stmt.sql:85
	 * - resources/sqlite/stmt.sql:105
	 * @param string $username
	 * @param string $address
	 * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, int>
	 */
	public function addAddress(string $username, string $address, ) : Generator {
		$this->conn->executeInsert("alias.add.address", ["username" => $username, "address" => $address, ], yield Await::RESOLVE, yield Await::REJECT);
		return yield Await::ONCE;
	}

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql/stmt.sql:91
	 * - resources/sqlite/stmt.sql:111
	 * @param string $username
	 * @param int $clientRandomId
	 * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, int>
	 */
	public function addClientRandomId(string $username, int $clientRandomId, ) : Generator {
		$this->conn->executeInsert("alias.add.client_random_id", ["username" => $username, "clientRandomId" => $clientRandomId, ], yield Await::RESOLVE, yield Await::REJECT);
		return yield Await::ONCE;
	}

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql/stmt.sql:97
	 * - resources/sqlite/stmt.sql:117
	 * @param string $username
	 * @param string $deviceId
	 * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, int>
	 */
	public function addDeviceId(string $username, string $deviceId, ) : Generator {
		$this->conn->executeInsert("alias.add.device_id", ["username" => $username, "deviceId" => $deviceId, ], yield Await::RESOLVE, yield Await::REJECT);
		return yield Await::ONCE;
	}

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql/stmt.sql:103
	 * - resources/sqlite/stmt.sql:123
	 * @param string $username
	 * @param string $selfSignedId
	 * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, int>
	 */
	public function addSelfSignedId(string $username, string $selfSignedId, ) : Generator {
		$this->conn->executeInsert("alias.add.self_signed_id", ["username" => $username, "selfSignedId" => $selfSignedId, ], yield Await::RESOLVE, yield Await::REJECT);
		return yield Await::ONCE;
	}

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql/stmt.sql:109
	 * - resources/sqlite/stmt.sql:129
	 * @param string $username
	 * @param string $xuid
	 * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, int>
	 */
	public function addXuid(string $username, string $xuid, ) : Generator {
		$this->conn->executeInsert("alias.add.xuid", ["username" => $username, "xuid" => $xuid, ], yield Await::RESOLVE, yield Await::REJECT);
		return yield Await::ONCE;
	}

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql/stmt.sql:41
	 * - resources/sqlite/stmt.sql:41
	 * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, int>
	 */
	public function deleteOldPlayers() : Generator {
		$this->conn->executeChange("alias.delete_old_players", [], yield Await::RESOLVE, yield Await::REJECT);
		return yield Await::ONCE;
	}

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql/stmt.sql:49
	 * - resources/sqlite/stmt.sql:53
	 * @param string $username
	 * @param ?string $extraAddress
	 * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, list<array<string, mixed>>>
	 */
	public function getAltAddress(string $username, ?string $extraAddress, ) : Generator {
		$this->conn->executeSelect("alias.get_alt.address", ["username" => $username, "extraAddress" => $extraAddress, ], yield Await::RESOLVE, yield Await::REJECT);
		return yield Await::ONCE;
	}

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql/stmt.sql:56
	 * - resources/sqlite/stmt.sql:64
	 * @param string $username
	 * @param ?int $extraClientRandomId
	 * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, list<array<string, mixed>>>
	 */
	public function getAltClientRandomId(string $username, ?int $extraClientRandomId, ) : Generator {
		$this->conn->executeSelect("alias.get_alt.client_random_id", ["username" => $username, "extraClientRandomId" => $extraClientRandomId, ], yield Await::RESOLVE, yield Await::REJECT);
		return yield Await::ONCE;
	}

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql/stmt.sql:63
	 * - resources/sqlite/stmt.sql:75
	 * @param string $username
	 * @param ?string $extraDeviceId
	 * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, list<array<string, mixed>>>
	 */
	public function getAltDeviceId(string $username, ?string $extraDeviceId, ) : Generator {
		$this->conn->executeSelect("alias.get_alt.device_id", ["username" => $username, "extraDeviceId" => $extraDeviceId, ], yield Await::RESOLVE, yield Await::REJECT);
		return yield Await::ONCE;
	}

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql/stmt.sql:70
	 * - resources/sqlite/stmt.sql:86
	 * @param string $username
	 * @param ?string $extraSelfSignedId
	 * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, list<array<string, mixed>>>
	 */
	public function getAltSelfSignedId(string $username, ?string $extraSelfSignedId, ) : Generator {
		$this->conn->executeSelect("alias.get_alt.self_signed_id", ["username" => $username, "extraSelfSignedId" => $extraSelfSignedId, ], yield Await::RESOLVE, yield Await::REJECT);
		return yield Await::ONCE;
	}

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql/stmt.sql:77
	 * - resources/sqlite/stmt.sql:97
	 * @param string $username
	 * @param ?string $extraXuid
	 * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, list<array<string, mixed>>>
	 */
	public function getAltXuid(string $username, ?string $extraXuid, ) : Generator {
		$this->conn->executeSelect("alias.get_alt.xuid", ["username" => $username, "extraXuid" => $extraXuid, ], yield Await::RESOLVE, yield Await::REJECT);
		return yield Await::ONCE;
	}

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql/stmt.sql:33
	 * - resources/sqlite/stmt.sql:33
	 * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, int>
	 */
	public function initTables() : Generator {
		$this->conn->executeChange("alias.init.tables", [], yield Await::RESOLVE, yield Await::REJECT);
		return yield Await::ONCE;
	}

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql/stmt.sql:38
	 * - resources/sqlite/stmt.sql:38
	 * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, list<array<string, mixed>>>
	 */
	public function loadOldPlayers() : Generator {
		$this->conn->executeSelect("alias.load_old_players", [], yield Await::RESOLVE, yield Await::REJECT);
		return yield Await::ONCE;
	}
}